name: titlebar_buttons
description: A package which provides most of the titlebar buttons from windows, linux and macos.
version: 1.0.0
homepage: https://github.com/gtk-flutter/titlebar_buttons

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

dependencies:
  change_case: ^2.0.1
  dbus: ^0.7.10
  flutter_svg: ^2.0.10+1
  gsettings: ^0.2.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ">=2.4.0 <3.0.0"

flutter:
  assets:
    - assets/themes/adwaita/
    - assets/themes/arc-dark/
    - assets/themes/arc-light/
    - assets/themes/breeze/
    - assets/themes/elementary/
    - assets/themes/flat-remix/
    - assets/themes/materia-dark/
    - assets/themes/materia-light/
    - assets/themes/nordic/
    - assets/themes/osx-arc/
    - assets/themes/pop-dark/
    - assets/themes/pop-light/
    - assets/themes/unity-dark/
    - assets/themes/unity-light/
    - assets/themes/vimix/
    - assets/themes/yaru/
